spring:
    datasource:
        space:
            hikari:
                connectionTimeout: 20000
                maximumPoolSize: 5
            url: jdbc:postgresql://localhost:5430/space
            username: postgres
            password: 123456
            driver-class-name: org.postgresql.Driver
            ddlSchema: update

    jpa:
        show-sql: true
        generate-ddl: true
        properties:
            hibernate:
                format_sql: true
                jdbc.lob.non_contextual_creation: true